# Generated by Django 5.1.1 on 2024-10-20 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('amount', models.IntegerField(default=255)),
                ('description', models.TextField(max_length=255)),
                ('date', models.DateField(auto_now_add=True)),
                ('category', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('amount', models.IntegerField(default=255)),
                ('description', models.TextField(max_length=255)),
                ('date', models.DateField(auto_now_add=True)),
                ('category', models.CharField(max_length=255)),
            ],
        ),
    ]
